const a = 1;
console.log("a :",a);
const b = "hello";
console.log("b :",b);
const c = true;
console.log("c :",c);
const d = 10;
console.log("d :",d);
let e = 10;
console.log("e :",e);
e = 20;
console.log("e :",e);
const myArray = [1, 2, 3];
console.log("myArray :",myArray);
const myObject = { x: 1, y: 2 };
console.log("myObject :",myObject);
const myObjects = [{ x: 1, y: 2 }, { x: 3, y: 4 }];
console.log("myObject :",myObject);